Repository rewardops/rewardops-sdk-node, pull requests merged in 2020-09, with the labels that each got.

#35 chore(release): v1.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement

#37 feat: add token cache & additional tests for the order recipient factory MX-1064
  jest.config.js
  lib/auth.js
  lib/resources/order-recipients.js
  lib/urls.js
  lib/utils/axios-helpers.js
  test/auth.test.js
  test/resources/v5/order-recipients.test.js
  test/utils/axios-helper.test.js
Labels: enhancement, refactor, tests

#38 fix: add missing `return` from `storeOrderRecipient` [MX-1106]
  lib/context.js
  lib/resources/order-recipients.js
  test/context.test.js
  test/resources/v5/order-recipients.test.js
Labels: bug

#36 docs: improve introductory documentation [MX-1073]
  README.md
  jsdoc.json
  lib/auth.js
  lib/config.js
  lib/context.js
  lib/resources/custom-categories.js
  lib/resources/items.js
  lib/resources/order-recipients.js
  lib/resources/orders.js
  lib/resources/rewards.js
  package-lock.json
  package.json
Labels: documentation, enhancement
